# Generated by Django 2.1.2 on 2018-10-28 03:21

from django.db import migrations, models

from _ckuhl import settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('file_path', models.FilePathField(match='*.md',
                                                   path=settings.RESOURCEFILES_DIR / 'blog' / 'flatpages',
                                                   primary_key=True,
                                                   recursive=True,
                                                   serialize=False,
                                                   unique=True)),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=64, unique=True)),
                ('title', models.TextField(unique=True)),
                ('category', models.TextField()),
                ('body', models.TextField(unique=True)),
            ],
        ),
    ]
