# Generated by Django 2.1.3 on 2018-11-11, modified to remove weird path update

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_make_body_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
