---
- hosts: ckuhl.com
  user: root
  roles:
  - configure

- hosts: localhost
  connection: local
  roles:
  - prepare

- hosts: ckuhl.com
  user: "{{ user.name }}"
  roles:
  - nginx
  - letsencrypt
  - deploy
