# Generated by Django 2.1.3 on 2018-11-11, modified to remove weird path update

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0002_add_optional_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='body',
            field=models.TextField(),
        ),
    ]
