---

project: # Project information
  domain: "{{ inventory_hostname }}"
  name: ckuhl
  version: "{{ version }}" # NOTE: This variable added on the command line `... --extra-vars "version=a0f8e3e1" ...`
  versioned_name: "ckuhl-{{ version }}"

user: # User that will manage the server
  name: ckuhl
  password: $6$mi9X5WdbkNobMbu$NqHAtKLVEBHSFsImcYRrSc4BnGX661WzGMtaoIIvxefcttbncLRcKaquyvRLLtFEtgnQ/3JvJsqCkFNn5f2MU.
  groups: sudo

path:
  local:
    file:
      code: "{{ inventory_dir }}/roles/deploy/files/code.zip"
      static: "{{ inventory_dir }}/roles/deploy/files/static.zip"
      resources: "{{ inventory_dir }}/roles/deploy/files/resources.zip"
      requirements: "{{ inventory_dir }}/roles/deploy/files/requirements.txt"

  remote:
    dir:
      home: /home/{{ user.name }}
      resources: /home/{{ user.name }}/resources
      scripts: /home/{{ user.name }}/scripts
      media: /home/{{ user.name }}/media
      static: /home/{{ user.name }}/static
      version: /home/{{ user.name }}/{{ project.version }}
      venv: /home/{{ user.name }}/{{ project.version }}/env
      code: /home/{{ user.name }}/{{ project.version }}/{{ project.name }}

    file:
      settings: /home/{{ user.name }}/{{ project.version }}/{{ project.name }}/__django/settings.py
      version: /home/{{ user.name }}/.version # records active version of the project
      requirements: /home/{{ user.name }}/{{ project.version }}/requirements.txt
      uwsgi_socket: /tmp/{{ project.versioned_name }}.sock
      db: /home/{{ user.name }}/db.sqlite3
