#!/bin/bash
# location of log file
LOG=/var/log/letsencrypt-renew.log

# note in log if run by cron or by user
if [ -t 1 ]; then
        echo "[cron]" >> $LOG
else
        echo "[user]" >> $LOG
fi

# timestamp it
echo $(date) >> $LOG

# actually renew the cert
~/certbot-auto renew >> $LOG

