---

- name: all __pycache__ directories found
  find:
    paths: "{{ path.local.dir.code }}"
    patterns: "__pycache__"
    file_type: directory
    recurse: yes
  register: directoriesToRemove

- name: all __pycache__ directories deleted
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ directoriesToRemove.files }}"

- name: code in an archive
  archive:
    path: "{{ path.local.dir.code }}"
    dest: "{{ path.local.file.code }}"
    format: gz

- name: static content in an archive
  archive:
    path: "{{ path.local.dir.static }}"
    dest: "{{ path.local.file.static }}"
    format: gz

- name: resources in an archive
  archive:
    path: "{{ path.local.dir.resources }}"
    dest: "{{ path.local.file.resources }}"
    format: gz

- name: requirements.txt generated
  command: pipenv lock -r
  register: projectRequirements
  changed_when: false

- name: save requirements
  copy:
    content: "{{ projectRequirements.stdout }}"
    dest: "{{ path.local.file.requirements }}"
