---
- name: Project requirements installed
  apt:
    name:
    - python3.7-dev
    - python3-pip
    - virtualenv
    - unzip
    - gcc # required to install Python uWSGI module
    state: present
  become: yes

- name: Base directory exists
  file:
    path: "{{ path.remote.dir.version }}"
    state: directory
    mode: 0755

- name: Code on server
  unarchive:
    src: "{{ path.local.file.code }}"
    dest: "{{ path.remote.dir.version }}"

- name: Requirements on server
  copy:
    src: "{{ path.local.file.requirements }}"
    dest: "{{ path.remote.file.requirements }}"

- name: Virtual environment exists
  pip:
    requirements: "{{ path.remote.file.requirements }}"
    virtualenv: "{{ path.remote.dir.venv }}"
    virtualenv_python: python3.7

- name: Production settings are live
  template:
    src: settings.py.j2
    dest: "{{ path.remote.file.settings }}"

- name: Static content on server
  unarchive:
    src: "{{ path.local.file.static }}"
    dest: "{{ path.remote.dir.home }}"

- name: Resources on server
  unarchive:
    src: "{{ path.local.file.resources }}"
    dest: "{{ path.remote.dir.home }}"

- name: Systemd service exists
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ project.versioned_name }}.service
  become: yes
  notify: restart project service

- name: uWSGI config is in project root
  template:
    src: uwsgi.ini.j2
    dest: "{{ path.remote.dir.version }}/uwsgi.ini"
  notify: restart project service

# Deploy NGINX config
# Extracted from project.yml because this depends on specific folders
# Also depends on uWSGI socket existing
- name: Nginx config is available
  template:
    src: uwsgi-letsencrypt-nginx.config.j2
    dest: "{{ nginx.sites.available }}/{{ project.versioned_name }}"
  become: yes

- name: Nginx config is valid
  command: nginx -t
  become: true
  changed_when: false # this never "changes", can only succeed / fail the entire deploy

# TODO: Run tests against new code before switching over
#  - name: running tests

# TODO: Move Django DB to new location (in settings.py)
#- name: Ensure DB exists
#  file:
#    path: "{{ path.remote.file.db }}"
#    state: touch

# FIXME: There shouldn't be migrations, but presently they occur due to Pathlib problems
- name: DB schema has migrations (i.e. makemigrations)
  command: "{{ path.remote.dir.venv }}/bin/python {{ path.remote.dir.code }}/manage.py makemigrations"
  register: doMigrateResults
  changed_when: "'Migrations for' in doMigrateResults.stdout"

- name: DB schema up to date (i.e. migrate)
  command: "{{ path.remote.dir.venv }}/bin/python {{ path.remote.dir.code }}/manage.py migrate"
  register: dbUpdateResults
  changed_when: "'No migrations to apply' not in dbUpdateResults.stdout"
  failed_when: "'Your models have changes' in dbUpdateResults.stdout"

- name: Check if previous version is running
  stat:
    path: "{{ path.remote.file.version }}"
  register: existingDeployment

- name: Load the previous version's name (if it exists)
  shell: cat {{ path.remote.file.version }}
  register: existingDeploymentVersion
  when: existingDeployment.stat.exists == true

- name: Nginx config enabled
  file:
    src: "{{ nginx.sites.available }}/{{ project.versioned_name }}"
    dest: "{{ nginx.sites.enabled }}/{{ project.versioned_name }}"
    state: link
  become: yes
  notify: restart nginx service

- name: Store that live version is {{ project.version }} on the machine
  template:
    src: live_version.j2
    dest: "{{ path.remote.file.version }}"

- name: Previous version stopped
  service:
    name: "{{ project.name }}-{{ existingDeploymentVersion.stdout }}"
    state: stopped
    enabled: False
  become: yes
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout

- name: Previous version's code removed
  file:
    path: "{{ path.remote.dir.version }}/{{ existingDeploymentVersion.stdout }}"
    state: absent
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout

- name: Previous version's systemd serviced removed
  file:
    path: /etc/systemd/system/{{ project.name }}-{{ existingDeploymentVersion.stdout }}.service
    state: absent
  become: yes
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout

- name: Previous version's nginx config disabled
  file:
    path: "{{ nginx.sites.enabled }}/{{ project.name }}-{{ existingDeploymentVersion.stdout }}"
    state: absent
  become: yes
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout
  notify: restart nginx service

- name: Previous version's nginx config removed
  file:
    path: "{{ nginx.sites.available }}/{{ project.name }}-{{ existingDeploymentVersion.stdout }}"
    state: absent
  become: yes
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout
  notify: restart nginx service

- name: Previous version's code removed
  file:
    state: absent
    path: "{{ path.remote.dir.home }}/{{ existingDeploymentVersion.stdout }}"
  when: existingDeployment.stat.exists == true and project.version not in existingDeploymentVersion.stdout
